Push after init works
Passing all tests.

diff --git a/lib/git-subrepo b/lib/git-subrepo
--- a/lib/git-subrepo
+++ b/lib/git-subrepo
@@ -456,6 +456,7 @@ subrepo:pull() {
 # Push a properly merged subrepo branch upstream:
 subrepo:push() {
   local branch_name="$branch"
+  local new_upstream=false
   if [ -z "$branch_name" ]; then
     o "Fetch the upstream: $subrepo_remote ($subrepo_branch):"
     FAIL=false OUT=false CALL subrepo:fetch
@@ -468,56 +469,64 @@ subrepo:push() {
         o "Pushing to new upstream: $subrepo_remote ($subrepo_branch):"
         RUN git push \
           "$subrepo_remote" "$subrepo_commit:refs/heads/$subrepo_branch"
-        return
+        new_upstream=true
+      else
+        error "Fetch for push failed: $output"
       fi
-      error "Fetch for push failed: $output"
-    fi
+    else
+      branch_name="subrepo-push/$subdir"
+      if git:branch-exists "$branch_name"; then
+        error "There is a previous push branch '$branch_name'. Delete it first."
+      fi
 
-    branch_name="subrepo-push/$subdir"
-    if git:branch-exists "$branch_name"; then
-      error "There is a previous push branch '$branch_name'. Delete it first."
-    fi
+      o "Create subrepo branch '$branch_name':"
+      CALL subrepo:branch "$branch_name"
+      if ! OK; then return; fi
 
-    o "Create subrepo branch '$branch_name':"
-    CALL subrepo:branch "$branch_name"
-    if ! OK; then return; fi
-
-    o "git rebase $refs_subrepo_fetch $branch_name"
-    FAIL=false OUT=true RUN git rebase "$refs_subrepo_fetch" "$branch_name"
-    if ! OK; then
-      o "The rebase command failed:"$'\n'----$'\n'"$output"$'\n'----
-      CODE=2; return
+      o "git rebase $refs_subrepo_fetch $branch_name"
+      FAIL=false OUT=true RUN git rebase "$refs_subrepo_fetch" "$branch_name"
+      if ! OK; then
+        o "The rebase command failed:"$'\n'----$'\n'"$output"$'\n'----
+        CODE=2; return
+      fi
+      RUN git checkout "$original_head_branch"
     fi
-    RUN git checkout "$original_head_branch"
   else
     if ! git:rev-exists "$branch_name"; then
       error "'$branch_name' is not a valid commit."
     fi
   fi
 
-  o "Make sure that '$branch_name' exists."
-  git:branch-exists "$branch_name" ||
-    error "No subrepo branch '$branch_name' to push."
+  if ! $new_upstream; then
+    o "Make sure that '$branch_name' exists."
+    git:branch-exists "$branch_name" ||
+      error "No subrepo branch '$branch_name' to push."
 
-  if ! "$force_wanted"; then
-    o "Make sure '$branch_name' contains the '$refs_subrepo_fetch' HEAD."
-    if ! git:commit-in-rev-list "$upstream_head_commit" "$branch_name"; then
-      error "Can't commit: '$branch_name' doesn't contain upstream HEAD."
+    if ! "$force_wanted"; then
+      o "Make sure '$branch_name' contains the '$refs_subrepo_fetch' HEAD."
+      if ! git:commit-in-rev-list "$upstream_head_commit" "$branch_name"; then
+        error "Can't commit: '$branch_name' doesn't contain upstream HEAD."
+      fi
+    fi
+
+    local force=
+    "$force_wanted" && force=--force
+
+    o "Push branch '$branch_name' to '$subrepo_remote' ($subrepo_branch)."
+    RUN git push $force "$subrepo_remote" "$branch_name":"$subrepo_branch"
+
+    o "Create ref '$refs_subrepo_push' for branch '$branch_name'."
+    git:make-ref "$refs_subrepo_push" "$branch_name"
+
+    if [ "$branch_name" == "subrepo-push/$subdir" ]; then
+      o "Remove branch '$branch_name'"
+      RUN git branch -D "$branch_name"
     fi
   fi
 
-  local force=
-  "$force_wanted" && force=--force
-
-  o "Push branch '$branch_name' to '$subrepo_remote' ($subrepo_branch)."
-  RUN git push $force "$subrepo_remote" "$branch_name":"$subrepo_branch"
-
-  o "Create ref '$refs_subrepo_push' for branch '$branch_name'."
-  git:make-ref "$refs_subrepo_push" "$branch_name"
-
-  if [ "$branch_name" == "subrepo-push/$subdir" ]; then
-    o "Remove branch '$branch_name'"
-    RUN git branch -D "$branch_name"
+  if $update_wanted; then
+    o "Put updates into '$subdir/.gitrepo' file."
+    update-gitrepo-file
   fi
 }
 
