Testing new push tactics.

diff --git a/lib/git-subrepo b/lib/git-subrepo
--- a/lib/git-subrepo
+++ b/lib/git-subrepo
@@ -518,6 +518,9 @@ subrepo:push() {
         o "Pushing to new upstream: $subrepo_remote ($subrepo_branch)."
         RUN git push \
           "$subrepo_remote" "$subrepo_commit:refs/heads/$subrepo_branch"
+
+        o "We have pushed, now we need to fetch this information"
+        OUT=false CALL subrepo:fetch
         new_upstream=true
       else
         error "Fetch for push failed: $output"
@@ -530,80 +533,82 @@ subrepo:push() {
         error "Local branch is not updated, perform pull or use "\
 "'--force' to always trust local branch in conflicts"
       fi
+    fi
 
-      branch_name="subrepo-push/$subdir"
-      if git:branch-exists "$branch_name"; then
-        error "There is a previous push branch '$branch_name'. "\
+    branch_name="subrepo-push/$subdir"
+    if git:branch-exists "$branch_name"; then
+      error "There is a previous push branch '$branch_name'. "\
 "Delete it first."
-      fi
+    fi
 
-      o "Create subrepo branch '$branch_name'."
-      CALL subrepo:branch "$branch_name"
+    o "Create subrepo branch '$branch_name'."
+    CALL subrepo:branch "$branch_name"
 
-      o "Find ancestor with same treehash."
-      if ! subrepo:merge-base "$refs_subrepo_fetch" "$branch_name"; then
-        error "Can't find a common ancestor between $refs_subrepo_fetch "\
+    o "Find ancestor with same treehash."
+    if ! subrepo:merge-base "$refs_subrepo_fetch" "$branch_name"; then
+      error "Can't find a common ancestor between $refs_subrepo_fetch "\
 "and $branch_name. This might be the case if someone used push --force on "\
 "the subrepo. You need to find out why and possibly reclone the subrepo."
-      fi
+    fi
 
-      if $first_on_both ; then
-        o "The subrepo:merge-base function reports same location."
-        RUN git branch -D "$branch_name"
-        RUN git checkout "$original_head_branch"
+    if $first_on_both ; then
+      o "The subrepo:merge-base function reports same location."
+      RUN git branch -D "$branch_name"
+      RUN git checkout "$original_head_branch"
+      if $new_upstream ; then
+        OK=true
+      else
         OK=false
         CODE=-2
-        return
       fi
-
-      o "Set a common ancestor."
-      RUN git rebase --onto "$new_parent" "$old_parent" "$branch_name"
-
-      if [ $force_wanted = false ]; then
-        # Theirs in this case will ignore upstream and simply push our changes
-        # without conflict
-        o "Run 'git rebase -X theirs $refs_subrepo_fetch $branch_name'."
-        FAIL=false OUT=true RUN git rebase -X theirs \
-            "$refs_subrepo_fetch" "$branch_name"
-        if ! OK; then
-          say "The rebase command failed:"$'\n'----$'\n'"$output"$'\n'----
-          CODE=2;
-          return;
-        fi
-      fi
-
-      RUN git checkout "$original_head_branch"
+      return
     fi
+
+    o "Set a common ancestor."
+    RUN git rebase --onto "$new_parent" "$old_parent" "$branch_name"
+
+    if [ $force_wanted = false ]; then
+      # Theirs in this case will ignore upstream and simply push our changes
+      # without conflict
+      o "Run 'git rebase -X theirs $refs_subrepo_fetch $branch_name'."
+      FAIL=false OUT=true RUN git rebase -X theirs \
+          "$refs_subrepo_fetch" "$branch_name"
+      if ! OK; then
+        say "The rebase command failed:"$'\n'----$'\n'"$output"$'\n'----
+        CODE=2;
+        return;
+      fi
+    fi
+
+    RUN git checkout "$original_head_branch"
   else
     if ! git:rev-exists "$branch_name"; then
       error "'$branch_name' is not a valid commit."
     fi
   fi
 
-  if ! $new_upstream; then
-    o "Make sure that '$branch_name' exists."
-    git:branch-exists "$branch_name" ||
-      error "No subrepo branch '$branch_name' to push."
+  o "Make sure that '$branch_name' exists."
+  git:branch-exists "$branch_name" ||
+    error "No subrepo branch '$branch_name' to push."
 
-    if ! "$force_wanted"; then
-      o "Make sure '$branch_name' contains the '$refs_subrepo_fetch' HEAD."
-      if ! git:commit-in-rev-list "$upstream_head_commit" "$branch_name"; then
-        error "Can't commit: '$branch_name' doesn't contain upstream HEAD."
-      fi
+  if ! "$force_wanted"; then
+    o "Make sure '$branch_name' contains the '$refs_subrepo_fetch' HEAD."
+    if ! git:commit-in-rev-list "$upstream_head_commit" "$branch_name"; then
+      error "Can't commit: '$branch_name' doesn't contain upstream HEAD."
     fi
+  fi
 
-    local force="$force_wanted" && force=--force
+  local force="$force_wanted" && force=--force
 
-    o "Push branch '$branch_name' to '$subrepo_remote' ($subrepo_branch)."
-    RUN git push $force "$subrepo_remote" "$branch_name":"$subrepo_branch"
+  o "Push branch '$branch_name' to '$subrepo_remote' ($subrepo_branch)."
+  RUN git push $force "$subrepo_remote" "$branch_name":"$subrepo_branch"
 
-    o "Create ref '$refs_subrepo_push' for branch '$branch_name'."
-    git:make-ref "$refs_subrepo_push" "$branch_name"
+  o "Create ref '$refs_subrepo_push' for branch '$branch_name'."
+  git:make-ref "$refs_subrepo_push" "$branch_name"
 
-    if [ "$branch_name" == "subrepo-push/$subdir" ]; then
-      o "Remove branch '$branch_name'."
-      RUN git branch -D "$branch_name"
-    fi
+  if [ "$branch_name" == "subrepo-push/$subdir" ]; then
+    o "Remove branch '$branch_name'."
+    RUN git branch -D "$branch_name"
   fi
 
   if $update_wanted; then
