more refactoring

diff --git a/lib/git-subrepo b/lib/git-subrepo
--- a/lib/git-subrepo
+++ b/lib/git-subrepo
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# Copyright 2013 - Ingy döt Net <ingy@ingy.net>
+# Copyright 2013, 2014 - Ingy döt Net <ingy@ingy.net>
 #
 
 # Exit on any errors:
@@ -39,16 +39,22 @@ X,debug     Turn on -x Bash debugging
 #------------------------------------------------------------------------------
 main() {
   # Define globals:
-  local command= command_arguments=() subrepo_branch=master
+  local command= command_arguments=()
   local quiet_output=false verbose_output=false
+  local subrepo_branch=master
 
   # Check environment and parse CLI options:
-  setup
+  assert-sane-env
   get-opts "$@"
 
-  # Run the command:
+  # Make sure command exists:
   can "command:$command" ||
     error "unknown 'git subrepo' command: '$command'\n"
+
+  # Make sure repo is in the proper state:
+  [ $command == help ] || assert-ready
+
+  # Run the command:
   "command:$command" "${command_arguments[@]}"
 }
 
@@ -61,22 +67,23 @@ command:help() {
 
 # `git subrepo pull …` command:
 command:clone() {
-  # Define local variables:
-  local subrepo_url="${1:?"subrepo url required"}"
-  local subdir="$(get-subdir "$2")"
-  local gitrepo="$subdir/.gitrepo"
+  local subrepo_remote="${1:?"subrepo remote url required"}"
+  local subdir gitrepo
   local head_commit subrepo_commit tree_commit update_commit merge_commit
 
-  # Setup:
+  # Set subdir and gitrepo values:
+  set-subdir "$2"
+  gitrepo="$subdir/.gitrepo"
+
+  # Subdir must not already exist, for clone operation:
   assert-empty $subdir
-  assert-ready
 
   # Get the current HEAD commit:
   head_commit=$(git rev-parse HEAD)
 
   # Fetch all the git objects from the subrepo/branch:
-  git fetch --quiet "$subrepo_url" "$subrepo_branch" 2> /dev/null ||
-    error "command failed: git fetch $subrepo_url $subrepo_branch"
+  git fetch --quiet "$subrepo_remote" "$subrepo_branch" 2> /dev/null ||
+    error "command failed: git fetch $subrepo_remote $subrepo_branch"
 
   # Get the subrepo HEAD commit:
   subrepo_commit="$(git rev-parse FETCH_HEAD)"
@@ -92,7 +99,8 @@ command:clone() {
 
   # Create a commit object from the tree:
   update_commit="$(
-    action-message cloned | git commit-tree \
+    action-message cloned |
+    git commit-tree \
       "$(git log --max-count=1 --format=%T $subrepo_commit)" \
       -p $head_commit
   )"
@@ -105,31 +113,27 @@ command:clone() {
       -p $update_commit
   )"
 
-  # Set HEAD:
+  # Set HEAD ref:
   git reset "$merge_commit"
 
   # Add/amend the subdir/.gitrepo file:
   update-gitrepo "$update_commit"
 
   # Successful command output:
-  say "git subrepo '$subrepo_url' cloned into '$subdir'"
+  say "git subrepo '$subrepo_remote' cloned into '$subdir'"
 }
 
 # `git subrepo pull …` command:
 command:pull() {
-  # Define local variables:
-  local subdir gitrepo subrepo_url subrepo_branch subrepo_prev
+  local subdir gitrepo subrepo_remote subrepo_branch subrepo_former
   local subrepo_commit subrepo_old_commit update_commit
 
-  # Setup:
-  set-subdir "$1"
-  assert-ready
-  assert-clean
-  read-gitrepo
+  # Read current subrepo state:
+  get-subdir-state "$1"
 
   # Fetch the current subrepo objects:
-  git fetch --quiet "$subrepo_url" "$subrepo_branch" 2> /dev/null ||
-    die "failure: git fetch $subrepo_url $subrepo_branch"
+  git fetch --quiet "$subrepo_remote" "$subrepo_branch" 2> /dev/null ||
+    die "failure: git fetch $subrepo_remote $subrepo_branch"
 
   # Get the current subrepo HEAD commit:
   subrepo_commit=$(git rev-parse FETCH_HEAD)
@@ -142,9 +146,10 @@ command:pull() {
 
   # Create the update commit:
   update_commit="$(
-    action-message pulled | git commit-tree \
+    action-message pulled |
+    git commit-tree \
       "$(git log --max-count=1 --format=%T "$subrepo_commit")" \
-      -p "$subrepo_prev"
+      -p "$subrepo_former"
   )"
 
   # Merge the update with the subtree strategy:
@@ -154,22 +159,36 @@ command:pull() {
   update-gitrepo "$update_commit"
 
   # Successful command output:
-  say "git subrepo '$subdir' pulled from '$subrepo_url' ($subrepo_branch)"
+  say "git subrepo '$subdir' pulled from '$subrepo_remote' ($subrepo_branch)"
 }
 
 # `git subrepo push …` command:
+
 command:push() {
-  local subdir gitrepo subrepo_url subrepo_branch subrepo_prev
+  local subdir gitrepo subrepo_remote subrepo_branch subrepo_former
   local subrepo_commit update_commit
 
-  # Setup:
-  set-subdir "$1"
-  assert-ready
-  assert-clean
-  read-gitrepo
+  # Read current subrepo state:
+  get-subdir-state "$1"
 
-  # TODO: git filter-branch
-  die $subrepo_old_commit
+  # Pull first:
+  git subrepo pull $subdir
+
+  local tmpdir=.git/subrepo
+  local gitdir=$PWD/.git
+  [ -e $tmpdir ] && error "$tmpdir exists. Delete first."
+
+  git clone .git $tmpdir
+  (
+    cd $tmpdir
+    git filter-branch \
+      --subdirectory-filter "$subdir" -- $subrepo_former..HEAD &> /dev/null
+#     head=$(git rev-parse HEAD)
+#     echo $head
+#     git reset --hard $subrepo_former
+  )
+  say OK
+  :
 }
 
 # `git subrepo status …` command:
@@ -181,16 +200,6 @@ command:status() {
 #------------------------------------------------------------------------------
 # Support functions:
 #------------------------------------------------------------------------------
-
-# Check git sanity:
-setup() {
-  type git &> /dev/null ||
-    error "can't find your 'git' command in '$PATH'"
-  local version="$(git --version)"
-  if [[ "$version" < "git version 1.7" ]]; then
-    error "requires git version 1.7 or higher; you have '$version'"
-  fi
-}
 
 # Parse command line options:
 get-opts() {
@@ -222,36 +231,69 @@ get-opts() {
   command_arguments=("$@")
 }
 
-# Set subdir and gitrepo vars:
+# Determine the correct subdir path to use:
 set-subdir() {
-  subdir="$(get-subdir "$1")"
+  local dir="$1"
+  if [ -z "$dir" ]; then
+    dir="${subrepo_remote##*/}"
+    dir="${dir%.git}"
+    [[ "$dir" =~ [a-zA-Z] ]] ||
+      error "can't determine subdir from '$subrepo_remote'"
+  fi
+  [[ "$dir" =~ ^/ ]] &&
+    error "subdir '$dir' should not be absolute path"
+  subdir="${dir%%/}"
+}
+
+# Set subdir and gitrepo vars:
+get-subdir-state() {
+  set-subdir "$1"
   gitrepo="$subdir/.gitrepo"
 
   if [ ! -f "$gitrepo" ]; then
     error "'$subdir' is not a subrepo"
   fi
+
+  # Read .gitrepo values:
+  subrepo_remote="$(git config --file="$gitrepo" subrepo.remote)"
+  subrepo_branch="$(git config --file="$gitrepo" subrepo.branch)"
+  subrepo_old_commit="$(git config --file="$gitrepo" subrepo.commit)"
+  subrepo_former="$(git config --file="$gitrepo" subrepo.former)"
 }
 
-# Determine the correct subdir path to use:
-get-subdir() {
-  local dir="$1"
-  if [ -z "$dir" ]; then
-    dir="${subrepo_url##*/}"
-    dir="${dir%.git}"
-    [[ "$dir" =~ [a-zA-Z] ]] ||
-      error "can't determine subdir from '$subrepo_url'"
+# Check git sanity:
+assert-sane-env() {
+  type git &> /dev/null ||
+    error "can't find your 'git' command in '$PATH'"
+  local version="$(git --version)"
+  if [[ "$version" < "git version 1.7" ]]; then
+    error "requires git version 1.7 or higher; you have '$version'"
   fi
-  [[ "$dir" =~ ^/ ]] &&
-    error "subdir '$dir' should not be absolute path"
-  dir="${dir%%/}"
-  echo "$dir"
 }
 
 # Make sure git repo is ready:
 assert-ready() {
-  if [ "$(git rev-parse --is-inside-work-tree 2>/dev/null)" != true ]; then
+  # In a work-tree:
+  [ "$(git rev-parse --is-inside-work-tree 2>/dev/null)" == true ] ||
     error "can't 'subrepo $command' outside a working tree."
-  fi
+
+  # HEAD exists:
+  git rev-parse --verify HEAD >/dev/null || die
+
+  # Repo is in a clean state:
+  git update-index -q --ignore-submodules --refresh
+  git diff-files --quiet --ignore-submodules ||
+    error "can't $action subrepo. Unstaged changes."
+  git diff-index --quiet --ignore-submodules HEAD ||
+    error "can't $action subrepo. Working tree has changes."
+  git diff-index --quiet --cached --ignore-submodules HEAD ||
+    error "can't $action subrepo. Index has changes."
+
+  # For now, only support actions from top of repo:
+  [ "$(git rev-parse --git-dir)" == '.git' ] ||
+    error "need to be at the top level directory of the repo."
+
+  :
 }
 
 # If subdir exists, make sure it is empty:
@@ -262,33 +304,13 @@ assert-empty() {
   fi
 }
 
-# Make sure repo is in a clean state:
-assert-clean() {
-  git rev-parse --verify HEAD >/dev/null || die
-  git update-index -q --ignore-submodules --refresh
-  git diff-files --quiet --ignore-submodules ||
-    error "can't $action subrepo. Unstaged changes."
-  git diff-index --quiet --ignore-submodules HEAD ||
-    error "can't $action subrepo. Working tree has changes."
-  git diff-index --quiet --cached --ignore-submodules HEAD ||
-    error "can't $action subrepo. Index has changes."
-  :
-}
-
-read-gitrepo() {
-  subrepo_url="$(git config --file="$gitrepo" subrepo.url)"
-  subrepo_branch="$(git config --file="$gitrepo" subrepo.branch)"
-  subrepo_old_commit="$(git config --file="$gitrepo" subrepo.commit)"
-  subrepo_prev="$(git config --file="$gitrepo" subrepo.prev)"
-}
-
 # Commit msg for an action commit:
 action-message() {
   action="$1"
   cat <<...
 subrepo $action into '$subdir/'
 
-subrepo url:    $subrepo_url
+subrepo remote: $subrepo_remote
 subrepo branch: $subrepo_branch
 subrepo commit: $subrepo_commit
 ...
@@ -297,12 +319,13 @@ subrepo commit: $subrepo_commit
 # Update the subdir/.gitrepo state file:
 update-gitrepo() {
   local change_commit="$1"
+  local subrepo_former="$change_commit"
   local short_commit=$(git rev-parse --short "$change_commit")
 
-  git config --file="$gitrepo" subrepo.url "$subrepo_url"
+  git config --file="$gitrepo" subrepo.remote "$subrepo_remote"
   git config --file="$gitrepo" subrepo.branch "$subrepo_branch"
   git config --file="$gitrepo" subrepo.commit "$subrepo_commit"
-  git config --file="$gitrepo" subrepo.prev "$change_commit"
+  git config --file="$gitrepo" subrepo.former "$change_commit"
   git add "$gitrepo"
   git commit \
     --quiet \
