Figured out simpler way to do this
If push remote branch doesn't exist, just push to it.

This should make the complete the `init` work.

diff --git a/lib/git-subrepo b/lib/git-subrepo
--- a/lib/git-subrepo
+++ b/lib/git-subrepo
@@ -464,21 +464,24 @@ subrepo:pull() {
 # Push a properly merged subrepo branch upstream:
 subrepo:push() {
   local branch_name="$branch"
-  local new_upstream=false
   if [ -z "$branch_name" ]; then
     o "Fetch the upstream: $subrepo_remote ($subrepo_branch):"
     FAIL=false OUT=false CALL subrepo:fetch
 
     if ! OK; then
+      # Check if we are pushing to a new upstream repo (or branch) and just
+      # push the commit directly. This is common after a `git subrepo init`:
       local re="^fatal: Couldn't find remote ref "
-      if [[ ! $output =~ $re ]]; then
-        error "Fetch failed: $output"
+      if [[ $output =~ $re ]]; then
+        o "Pushing to new upstream: $subrepo_remote ($subrepo_branch):"
+        RUN git push \
+          "$subrepo_remote" "$subrepo_commit:refs/heads/$subrepo_branch"
+        return
       fi
-      new_upstream=true
+      error "Fetch for push failed: $output"
     fi
 
     branch_name="subrepo-push/$subdir"
-
     if git:branch-exists "$branch_name"; then
       error "There is a previous push branch '$branch_name'. Delete it first."
     fi
@@ -489,15 +492,13 @@ subrepo:push() {
       CODE=-1; return
     fi
 
-    if ! $new_upstream; then
-      o "git rebase $refs_subrepo_fetch $branch_name"
-      FAIL=false OUT=true RUN git rebase "$refs_subrepo_fetch" "$branch_name"
-      if ! OK; then
-        o "The rebase command failed:"$'\n'----$'\n'"$output"$'\n'----
-        CODE=2; return
-      fi
-      RUN git checkout "$original_head_branch"
+    o "git rebase $refs_subrepo_fetch $branch_name"
+    FAIL=false OUT=true RUN git rebase "$refs_subrepo_fetch" "$branch_name"
+    if ! OK; then
+      o "The rebase command failed:"$'\n'----$'\n'"$output"$'\n'----
+      CODE=2; return
     fi
+    RUN git checkout "$original_head_branch"
   else
     if ! git:rev-exists "$branch_name"; then
       error "'$branch_name' is not a valid commit."
@@ -508,7 +509,7 @@ subrepo:push() {
   git:branch-exists "$branch_name" ||
     error "No subrepo branch '$branch_name' to push."
 
-  if ! "$force_wanted" && ! "$new_upstream"; then
+  if ! "$force_wanted"; then
     o "Make sure '$branch_name' contains the '$refs_subrepo_fetch' HEAD."
     if ! git:commit-in-rev-list "$upstream_head_commit" "$branch_name"; then
       error "Can't commit: '$branch_name' doesn't contain upstream HEAD."
