Pull recfactoring WIP

diff --git a/lib/git-subrepo b/lib/git-subrepo
--- a/lib/git-subrepo
+++ b/lib/git-subrepo
@@ -162,58 +162,62 @@ command:pull() {
     subrepo:pull-reclone
     say "Subrepo '$subdir' recloned from '$subrepo_remote' ($subrepo_branch)"
     return
+  else
+    subrepo:pull
+    say "Subrepo '$subdir' pulled from '$subrepo_remote' ($subrepo_branch)"
+    return
   fi
 
-  # Writes best common-ancestor to $subrepo_parent
-  get-best-common-ancestor-for-merge
-
-  OUT=true RUN git log --max-count=1 --format=%T "$upstream_head"
-
-  # Create a new commit object from the upstream subrepo HEAD^{tree} with a
-  # parent being the best common-ancestor just found:
-  OUT=true RUN git commit-tree "$output" -p "$subrepo_parent" \
-    -m "$(subrepo:commit-message)"
-  update_commit="$output"
-
-  # TODO:
-  # This merge can fail, so we need to checkout/merge/remerge instead.
-
-  # Merge the update with the subtree strategy:
-  RUN git merge --no-ff \
-    -s recursive -X subtree="$subdir" -X patience "$update_commit"
-
-  OK ||
-    error "Failed to pull '$subdir'."
-
-  # Now, if our subrepo pull has the same parent as the merge commit (i.e.
-  # HEAD^ equals HEAD^2^) then we don't need to clean
-  OUT=true RUN git rev-parse HEAD^
-  local headparent="$output"
-  OUT=true RUN git rev-parse HEAD^2^
-  if [ "$headparent" != "$output" ]; then
-    # Prune the merge history to keep things looking clean:
-    RUN git filter-branch -f \
-      --parent-filter "sed 's/ -p $subrepo_parent//'" \
-      -- "$update_commit"^..HEAD ^HEAD^
-
-    # The update_commit just got rewritten. Need new id:
-    FAIL=false OUT=true RUN git rev-parse HEAD^2
-    if ! OK; then
-      # This bit helps when there is no second parent- which occurs in certain
-      # workflows.
-      FAIL=false OUT=true RUN git rev-parse HEAD
-    fi
-    update_commit="$output"
-  fi
-
-  # Update the subdir/.gitrepo file:
-  update-gitrepo-file
-  RUN git add "$gitrepo"
-  RUN git commit --quiet --amend \
-    --message="Merge subrepo commit '$(git rev-parse --short "$update_commit")'"
-
-  # Successful command output:
-  say "Subrepo '$subdir' pulled from '$subrepo_remote' ($subrepo_branch)"
+#   # Writes best common-ancestor to $subrepo_parent
+#   get-best-common-ancestor-for-merge
+# 
+#   OUT=true RUN git log --max-count=1 --format=%T "$upstream_head"
+# 
+#   # Create a new commit object from the upstream subrepo HEAD^{tree} with a
+#   # parent being the best common-ancestor just found:
+#   OUT=true RUN git commit-tree "$output" -p "$subrepo_parent" \
+#     -m "$(subrepo:commit-message)"
+#   update_commit="$output"
+# 
+#   # TODO:
+#   # This merge can fail, so we need to checkout/merge/remerge instead.
+# 
+#   # Merge the update with the subtree strategy:
+#   RUN git merge --no-ff \
+#     -s recursive -X subtree="$subdir" -X patience "$update_commit"
+# 
+#   OK ||
+#     error "Failed to pull '$subdir'."
+# 
+#   # Now, if our subrepo pull has the same parent as the merge commit (i.e.
+#   # HEAD^ equals HEAD^2^) then we don't need to clean
+#   OUT=true RUN git rev-parse HEAD^
+#   local headparent="$output"
+#   OUT=true RUN git rev-parse HEAD^2^
+#   if [ "$headparent" != "$output" ]; then
+#     # Prune the merge history to keep things looking clean:
+#     RUN git filter-branch -f \
+#       --parent-filter "sed 's/ -p $subrepo_parent//'" \
+#       -- "$update_commit"^..HEAD ^HEAD^
+# 
+#     # The update_commit just got rewritten. Need new id:
+#     FAIL=false OUT=true RUN git rev-parse HEAD^2
+#     if ! OK; then
+#       # This bit helps when there is no second parent- which occurs in certain
+#       # workflows.
+#       FAIL=false OUT=true RUN git rev-parse HEAD
+#     fi
+#     update_commit="$output"
+#   fi
+# 
+#   # Update the subdir/.gitrepo file:
+#   update-gitrepo-file
+#   RUN git add "$gitrepo"
+#   RUN git commit --quiet --amend \
+#     --message="Merge subrepo commit '$(git rev-parse --short "$update_commit")'"
+# 
+#   # Successful command output:
+#   say "Subrepo '$subdir' pulled from '$subrepo_remote' ($subrepo_branch)"
 }
 
 # `git subrepo push <subdir>` command:
@@ -418,6 +422,17 @@ subrepo:clone() {
 
   # Commit this subrepo clone:
   RUN git commit -m "$(subrepo:commit-message)"
+}
+
+subrepo:pull() {
+  subrepo:branch
+
+  if [ "$merge_strategy" == rebase ]; then
+    git rebase "subrepo/$subdir" "subrepo/remote/$subdir"
+  else
+    die 43
+  fi
+  exit 0
 }
 
 subrepo:pull-reclone() {
@@ -751,6 +766,8 @@ get-command-options() {
   fi
   if [ -n "$merge_strategy" ]; then
     check_strategy
+  else
+    merge_strategy=rebase
   fi
 }
 
